name: Build ZMK firmware
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */2 *" # run every two months to keep artifacts from expiring

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main


  keymap_images:
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/draw_keymaps.yaml